from __future__ import annotations

from .text import normalize_for_search


LEGAL_KEYWORDS = [
    "dự thảo",
    "lấy ý kiến",
    "góp ý dự thảo",
    "nghị định",
    "thông tư",
    "quyết định",
    "nghị quyết",
    "chỉ thị",
    "luật",
    "pháp lệnh",
    "ban hành",
    "có hiệu lực",
    "sửa đổi",
    "bổ sung",
    "sửa đổi, bổ sung",
    "thay thế",
    "bãi bỏ",
    "hướng dẫn thi hành",
    "quy định chi tiết",
    "xử phạt",
    "vi phạm hành chính",
    "thủ tục hành chính",
    "điều kiện kinh doanh",
    "giấy phép",
    "cấp phép",
    "đăng ký",
    "thông báo",
    "báo cáo",
    "kiểm tra",
    "thanh tra",
    "hậu kiểm",
    "quy chuẩn",
    "tiêu chuẩn",
    "quy chế",
    "chính sách mới",
]

TOPIC_KEYWORDS = [
    "dữ liệu",
    "dữ liệu cá nhân",
    "bảo vệ dữ liệu cá nhân",
    "xử lý dữ liệu cá nhân",
    "chuyển dữ liệu cá nhân ra nước ngoài",
    "thu thập thông tin",
    "thu thập dữ liệu",
    "chia sẻ dữ liệu",
    "khai thác dữ liệu",
    "dữ liệu mở",
    "dữ liệu lớn",
    "quản trị dữ liệu",
    "trung tâm dữ liệu",
    "điện toán đám mây",
    "quyền riêng tư",
    "đời sống riêng tư",
    "bí mật cá nhân",
    "bảo mật thông tin",
    "an toàn thông tin",
    "an ninh mạng",
    "rò rỉ dữ liệu",
    "vi phạm dữ liệu",
    "trí tuệ nhân tạo",
    "hệ thống trí tuệ nhân tạo",
    "mô hình trí tuệ nhân tạo",
    "mô hình ngôn ngữ lớn",
    "dữ liệu huấn luyện",
    "nội dung do trí tuệ nhân tạo tạo ra",
    "tác phẩm do trí tuệ nhân tạo tạo ra",
    "giả mạo bằng công nghệ",
    "thuật toán",
    "tự động hóa",
    "khai thác văn bản và dữ liệu",
    "chuyển đổi số",
    "kinh tế số",
    "xã hội số",
    "công nghệ số",
    "công nghệ mới",
    "công nghệ cao",
    "công nghệ chiến lược",
    "luật công nghệ",
    "nền tảng số",
    "nền tảng trực tuyến",
    "nền tảng trung gian",
    "dịch vụ số",
    "dịch vụ số xuyên biên giới",
    "dịch vụ xuyên biên giới",
    "giao dịch xuyên biên giới",
    "cung cấp dịch vụ xuyên biên giới",
    "mạng xã hội",
    "ứng dụng di động",
    "phần mềm",
    "bản quyền phần mềm",
    "hệ thống thông tin",
    "thương mại điện tử",
    "sàn giao dịch thương mại điện tử",
    "website thương mại điện tử",
    "giao dịch điện tử",
    "hợp đồng điện tử",
    "chữ ký điện tử",
    "chữ ký số",
    "dịch vụ chứng thực chữ ký số",
    "định danh điện tử",
    "xác thực điện tử",
    "tài khoản định danh điện tử",
    "thanh toán điện tử",
    "trung gian thanh toán",
    "ví điện tử",
    "quảng cáo trực tuyến",
    "quảng cáo trên mạng",
    "quảng cáo xuyên biên giới",
    "nội dung quảng cáo",
    "người nổi tiếng",
    "người có ảnh hưởng",
    "phát trực tiếp",
    "bán hàng qua phát trực tiếp",
    "nội dung vi phạm",
    "gỡ bỏ nội dung",
    "kiểm duyệt nội dung",
    "thông tin sai sự thật",
    "tin giả",
    "sở hữu trí tuệ",
    "quyền sở hữu trí tuệ",
    "quyền tác giả",
    "quyền liên quan",
    "bản quyền",
    "tác phẩm",
    "tác phẩm số",
    "nội dung số",
    "sao chép tác phẩm",
    "sử dụng tác phẩm",
    "truyền đạt tác phẩm",
    "phân phối tác phẩm",
    "xâm phạm quyền tác giả",
    "xâm phạm quyền sở hữu trí tuệ",
    "thực thi quyền sở hữu trí tuệ",
    "giám định sở hữu trí tuệ",
    "nhãn hiệu",
    "sáng chế",
    "kiểu dáng công nghiệp",
    "bí mật kinh doanh",
    "chỉ dẫn địa lý",
    "giống cây trồng",
    "đơn đăng ký sở hữu công nghiệp",
    "hàng giả",
    "hàng hóa giả mạo nhãn hiệu",
    "huấn luyện trí tuệ nhân tạo",
    "sử dụng tác phẩm để huấn luyện trí tuệ nhân tạo",
    "dữ liệu huấn luyện trí tuệ nhân tạo",
    "cấp phép bản quyền",
    "giấy phép sử dụng nội dung",
    "tiền bản quyền",
    "quyền sao chép tạm thời",
    "ngoại lệ quyền tác giả",
    "giới hạn quyền tác giả",
    "dịch vụ viễn thông",
    "mạng Internet",
    "tên miền",
    "địa chỉ giao thức mạng",
    "dịch vụ trung gian",
    "dịch vụ lưu trữ",
    "dịch vụ mạng xã hội",
    "dịch vụ chia sẻ video",
    "dịch vụ nội dung thông tin trên mạng",
    "trò chơi điện tử trên mạng",
    "dịch vụ truyền hình, phim và nội dung trên Internet",
    "kiểm tra an ninh mạng",
    "đánh giá an ninh mạng",
    "bảo vệ hệ thống thông tin",
    "hệ thống thông tin quan trọng",
    "ứng cứu sự cố",
    "sự cố an toàn thông tin",
    "mã độc",
    "tấn công mạng",
    "lỗ hổng bảo mật",
    "kiểm thử xâm nhập",
]


def keyword_hits(text: str, keywords: list[str]) -> list[str]:
    haystack = normalize_for_search(text)
    hits = []

    for keyword in keywords:
        normalized_keyword = normalize_for_search(keyword)
        if normalized_keyword and normalized_keyword in haystack:
            hits.append(keyword)

    return sorted(set(hits))


def is_relevant_text(
    text: str,
    legal_keywords: list[str] | None = None,
    topic_keywords: list[str] | None = None,
    require_legal_keyword: bool = True,
    require_topic_keyword: bool = True,
) -> bool:
    legal_hits = keyword_hits(text, legal_keywords or LEGAL_KEYWORDS)
    topic_hits = keyword_hits(text, topic_keywords or TOPIC_KEYWORDS)

    if require_legal_keyword and not legal_hits:
        return False

    if require_topic_keyword and not topic_hits:
        return False

    return True
